### ISSUE TITLE
Магические значения

### ISSUE THREAD

**Issue by truenorthpaul** [melnyk-a/WaterPipes#2]
«Магические значения» не должны просто так встречаться в программном коде. Вместо них стоит использовать константы или перечисления с информативными идентификаторами или сопровождать программный код комментариями, описывающими причину использования данного магического значения и его смысл.

Значения, для которых данное правило не соблюдается:
- `"Pipe"` (выражение `if (name == "Pipe" || name == "Source")` в методе `WaterPipes.Commands.EditCommands.DeleteCommand.Create`).
- `"Source"` (выражение `if (name == "Pipe" || name == "Source")` в методе `WaterPipes.Commands.EditCommands.DeleteCommand.Create`).
- `"Pipe"` (выражение `if (objectArea[neighbor.X, neighbor.Y].Name == "Pipe")` в методе `WaterPipes.Commands.EditCommands.DeleteCommand.Create`).
- `"Source"` (выражение `if (!(neighbor.Equals(notInclude)) && name == "Source")` в методе `WaterPipes.Commands.EditCommands.DeleteCommand.IsNeighborSource`).
- `"Pipe"` (выражение `if (!(neighbor.Equals(notInclude)) && name == "Pipe")` в методе `WaterPipes.Commands.EditCommands.DeleteCommand.IsNeighborSource`).
- `"Source"` (выражение `if (name == "Source" || name == "Pipe")` в методе `WaterPipes.Commands.EditCommands.EnterCommand.Create`).
- `"Pipe"` (выражение `if (name == "Source" || name == "Pipe")` в методе `WaterPipes.Commands.EditCommands.EnterCommand.Create`).
- `"Source"` (выражение `if (gameBoard.ObjectArea[i, j].Name == "Source")` в методе `WaterPipes.Game.Objects.PipeLine.UpdateGameBoard`).
- `"Pipe"` (выражение `else if (gameBoard.ObjectArea[i, j].Name == "Pipe")` в методе `WaterPipes.Game.Objects.PipeLine.UpdateGameBoard`).

**Comment by melnyk-a** [comment]
Для того чтобы убрать магические значения, я в каждом классе добавила статическое свойство Name и каждый раз проводила бы с ним. Как вариант можно было бы получить имя класса и с помощью свойства GetType().Name. Что в данном случае было бы уместней?

**Comment by truenorthpaul** [comment]
Первый вариант лучше. Он не привязан к названию класса, которое может измениться.
